"""Shared register definitions for the APC UPS Modbus integration.

Based on 990-5702A-EN (Smart-UPS excluding SMT/SMX/SURTD/SRT).
"""

REGISTERS = [
    {
        "key": "status_word_0",
        "address": 0x0000,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "status_word_1",
        "address": 0x0001,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "status_word_2",
        "address": 0x0002,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "status_word_3",
        "address": 0x0003,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_state_of_charge",
        "address": 0x0005,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "runtime_remaining",
        "address": 0x0006,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_voltage",
        "address": 0x0007,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "load_amps",
        "address": 0x0009,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "nominal_output_voltage",
        "address": 0x000D,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "actual_output_voltage",
        "address": 0x000E,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "max_input_voltage",
        "address": 0x000F,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "min_input_voltage",
        "address": 0x0010,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "input_voltage",
        "address": 0x0011,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "input_frequency",
        "address": 0x0012,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "minimum_return_battery_capacity",
        "address": 0x001A,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "nominal_output_voltage_setting",
        "address": 0x001D,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "low_battery_duration",
        "address": 0x001F,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "ups_id",
        "address": 0x0022,
        "count": 8,
        "type": "ascii",
        "scale": 1,
        "ascii_width": 1,
    },
    {
        "key": "battery_current",
        "address": 0x004D,
        "count": 1,
        "type": "int16",
        "scale": 1,
    },
]
