# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Anthony Burow
# https://github.com/aburow/cyberpower-modbus-ha

"""Register definitions for CyberPower three-phase UPS devices (experimental)."""

from __future__ import annotations

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.sensor import SensorStateClass

from .const import (
    CyberPowerModbusBinarySensorDescription,
    CyberPowerModbusSensorDescription,
)

REGISTERS = [
    # Bypass voltage/current/frequency/power factor
    {"key": "bypass_voltage_phase_a", "address": 0x0001, "count": 1, "type": "uint16", "scale": 10},
    {"key": "bypass_voltage_phase_b", "address": 0x0002, "count": 1, "type": "uint16", "scale": 10},
    {"key": "bypass_voltage_phase_c", "address": 0x0003, "count": 1, "type": "uint16", "scale": 10},
    {"key": "bypass_current_phase_a", "address": 0x0004, "count": 1, "type": "uint16", "scale": 10},
    {"key": "bypass_current_phase_b", "address": 0x0005, "count": 1, "type": "uint16", "scale": 10},
    {"key": "bypass_current_phase_c", "address": 0x0006, "count": 1, "type": "uint16", "scale": 10},
    {"key": "bypass_frequency_phase_a", "address": 0x0007, "count": 1, "type": "uint16", "scale": 100},
    {"key": "bypass_frequency_phase_b", "address": 0x0008, "count": 1, "type": "uint16", "scale": 100},
    {"key": "bypass_frequency_phase_c", "address": 0x0009, "count": 1, "type": "uint16", "scale": 100},
    {"key": "bypass_pf_phase_a", "address": 0x000A, "count": 1, "type": "uint16", "scale": 100},
    {"key": "bypass_pf_phase_b", "address": 0x000B, "count": 1, "type": "uint16", "scale": 100},
    {"key": "bypass_pf_phase_c", "address": 0x000C, "count": 1, "type": "uint16", "scale": 100},
    # Input measurements
    {"key": "input_voltage_phase_a", "address": 0x000D, "count": 1, "type": "uint16", "scale": 10},
    {"key": "input_voltage_phase_b", "address": 0x000E, "count": 1, "type": "uint16", "scale": 10},
    {"key": "input_voltage_phase_c", "address": 0x000F, "count": 1, "type": "uint16", "scale": 10},
    {"key": "input_current_phase_a", "address": 0x0010, "count": 1, "type": "uint16", "scale": 10},
    {"key": "input_current_phase_b", "address": 0x0011, "count": 1, "type": "uint16", "scale": 10},
    {"key": "input_current_phase_c", "address": 0x0012, "count": 1, "type": "uint16", "scale": 10},
    {"key": "input_frequency_phase_a", "address": 0x0013, "count": 1, "type": "uint16", "scale": 100},
    {"key": "input_frequency_phase_b", "address": 0x0014, "count": 1, "type": "uint16", "scale": 100},
    {"key": "input_frequency_phase_c", "address": 0x0015, "count": 1, "type": "uint16", "scale": 100},
    {"key": "input_pf_phase_a", "address": 0x0016, "count": 1, "type": "uint16", "scale": 100},
    {"key": "input_pf_phase_b", "address": 0x0017, "count": 1, "type": "uint16", "scale": 100},
    {"key": "input_pf_phase_c", "address": 0x0018, "count": 1, "type": "uint16", "scale": 100},
    # Output measurements
    {"key": "output_voltage_phase_a", "address": 0x0019, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_voltage_phase_b", "address": 0x001A, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_voltage_phase_c", "address": 0x001B, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_current_phase_a", "address": 0x001C, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_current_phase_b", "address": 0x001D, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_current_phase_c", "address": 0x001E, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_frequency_phase_a", "address": 0x001F, "count": 1, "type": "uint16", "scale": 100},
    {"key": "output_frequency_phase_b", "address": 0x0020, "count": 1, "type": "uint16", "scale": 100},
    {"key": "output_frequency_phase_c", "address": 0x0021, "count": 1, "type": "uint16", "scale": 100},
    {"key": "output_pf_phase_a", "address": 0x0022, "count": 1, "type": "uint16", "scale": 100},
    {"key": "output_pf_phase_b", "address": 0x0023, "count": 1, "type": "uint16", "scale": 100},
    {"key": "output_pf_phase_c", "address": 0x0024, "count": 1, "type": "uint16", "scale": 100},
    {"key": "output_apparent_power_phase_a", "address": 0x0025, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_apparent_power_phase_b", "address": 0x0026, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_apparent_power_phase_c", "address": 0x0027, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_active_power_phase_a", "address": 0x0028, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_active_power_phase_b", "address": 0x0029, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_active_power_phase_c", "address": 0x002A, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_reactive_power_phase_a", "address": 0x002B, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_reactive_power_phase_b", "address": 0x002C, "count": 1, "type": "uint16", "scale": 10},
    {"key": "output_reactive_power_phase_c", "address": 0x002D, "count": 1, "type": "uint16", "scale": 10},
    {"key": "load_percent_phase_a", "address": 0x002E, "count": 1, "type": "uint16", "scale": 10},
    {"key": "load_percent_phase_b", "address": 0x002F, "count": 1, "type": "uint16", "scale": 10},
    {"key": "load_percent_phase_c", "address": 0x0030, "count": 1, "type": "uint16", "scale": 10},
    {"key": "environment_temperature", "address": 0x0031, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_voltage", "address": 0x0032, "count": 1, "type": "uint16", "scale": 10},
    {"key": "battery_current", "address": 0x0034, "count": 1, "type": "int16", "scale": 10},
    {"key": "battery_temperature", "address": 0x0036, "count": 1, "type": "uint16", "scale": 10},
    {"key": "battery_runtime_remaining", "address": 0x0037, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_capacity", "address": 0x0038, "count": 1, "type": "uint16", "scale": 1},
    # Status and mode registers
    {"key": "load_on_source", "address": 0x0051, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_status", "address": 0x0052, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_connected", "address": 0x0053, "count": 1, "type": "uint16", "scale": 1},
    {"key": "epo_active", "address": 0x0055, "count": 1, "type": "uint16", "scale": 1},
    {"key": "inverter_capacity_low", "address": 0x0056, "count": 1, "type": "uint16", "scale": 1},
    {"key": "input_fail", "address": 0x0058, "count": 1, "type": "uint16", "scale": 1},
    {"key": "bypass_sequence_fail", "address": 0x0059, "count": 1, "type": "uint16", "scale": 1},
    {"key": "bypass_voltage_fail", "address": 0x005A, "count": 1, "type": "uint16", "scale": 1},
    {"key": "bypass_fail", "address": 0x005B, "count": 1, "type": "uint16", "scale": 1},
    {"key": "bypass_overload", "address": 0x005C, "count": 1, "type": "uint16", "scale": 1},
    {"key": "bypass_overload_timeout", "address": 0x005D, "count": 1, "type": "uint16", "scale": 1},
    {"key": "bypass_untrack", "address": 0x005E, "count": 1, "type": "uint16", "scale": 1},
    {"key": "output_shorted", "address": 0x0060, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_eod", "address": 0x0061, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_test_result", "address": 0x0063, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_maintain_result", "address": 0x0065, "count": 1, "type": "uint16", "scale": 1},
    {"key": "manual_bypass", "address": 0x006A, "count": 1, "type": "uint16", "scale": 1},
    {"key": "battery_volt_low", "address": 0x006B, "count": 1, "type": "uint16", "scale": 1},
    {"key": "lost_redundant", "address": 0x0070, "count": 1, "type": "uint16", "scale": 1},
]

REGISTER_BLOCKS = [
    {
        "name": "measurements",
        "start_address": 0x0000,
        "count": 0x39,
        "registers": [
            0x0001,
            0x0002,
            0x0003,
            0x0004,
            0x0005,
            0x0006,
            0x0007,
            0x0008,
            0x0009,
            0x000A,
            0x000B,
            0x000C,
            0x000D,
            0x000E,
            0x000F,
            0x0010,
            0x0011,
            0x0012,
            0x0013,
            0x0014,
            0x0015,
            0x0016,
            0x0017,
            0x0018,
            0x0019,
            0x001A,
            0x001B,
            0x001C,
            0x001D,
            0x001E,
            0x001F,
            0x0020,
            0x0021,
            0x0022,
            0x0023,
            0x0024,
            0x0025,
            0x0026,
            0x0027,
            0x0028,
            0x0029,
            0x002A,
            0x002B,
            0x002C,
            0x002D,
            0x002E,
            0x002F,
            0x0030,
            0x0031,
            0x0032,
            0x0034,
            0x0036,
            0x0037,
            0x0038,
        ],
    },
    {
        "name": "status",
        "start_address": 0x0050,
        "count": 0x27,
        "registers": [
            0x0051,
            0x0052,
            0x0053,
            0x0055,
            0x0056,
            0x0058,
            0x0059,
            0x005A,
            0x005B,
            0x005C,
            0x005D,
            0x005E,
            0x0060,
            0x0061,
            0x0063,
            0x0065,
            0x006A,
            0x006B,
            0x0070,
        ],
    },
]

REGISTER_MAP = {reg["address"]: reg for reg in REGISTERS}


def get_sensor_descriptions() -> list[CyberPowerModbusSensorDescription]:
    """Return sensor descriptions for three-phase devices."""
    return [
        CyberPowerModbusSensorDescription(
            key="bypass_voltage_phase_a",
            name="Bypass Voltage Phase A",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="bypass_voltage_phase_a",
        ),
        CyberPowerModbusSensorDescription(
            key="bypass_voltage_phase_b",
            name="Bypass Voltage Phase B",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="bypass_voltage_phase_b",
        ),
        CyberPowerModbusSensorDescription(
            key="bypass_voltage_phase_c",
            name="Bypass Voltage Phase C",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="bypass_voltage_phase_c",
        ),
        CyberPowerModbusSensorDescription(
            key="input_voltage_phase_a",
            name="Input Voltage Phase A",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="input_voltage_phase_a",
        ),
        CyberPowerModbusSensorDescription(
            key="input_voltage_phase_b",
            name="Input Voltage Phase B",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="input_voltage_phase_b",
        ),
        CyberPowerModbusSensorDescription(
            key="input_voltage_phase_c",
            name="Input Voltage Phase C",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="input_voltage_phase_c",
        ),
        CyberPowerModbusSensorDescription(
            key="output_voltage_phase_a",
            name="Output Voltage Phase A",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_voltage_phase_a",
        ),
        CyberPowerModbusSensorDescription(
            key="output_voltage_phase_b",
            name="Output Voltage Phase B",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_voltage_phase_b",
        ),
        CyberPowerModbusSensorDescription(
            key="output_voltage_phase_c",
            name="Output Voltage Phase C",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_voltage_phase_c",
        ),
        CyberPowerModbusSensorDescription(
            key="output_current_phase_a",
            name="Output Current Phase A",
            native_unit_of_measurement="A",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_current_phase_a",
        ),
        CyberPowerModbusSensorDescription(
            key="output_current_phase_b",
            name="Output Current Phase B",
            native_unit_of_measurement="A",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_current_phase_b",
        ),
        CyberPowerModbusSensorDescription(
            key="output_current_phase_c",
            name="Output Current Phase C",
            native_unit_of_measurement="A",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_current_phase_c",
        ),
        CyberPowerModbusSensorDescription(
            key="output_active_power_phase_a",
            name="Output Active Power Phase A",
            native_unit_of_measurement="kW",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_active_power_phase_a",
        ),
        CyberPowerModbusSensorDescription(
            key="output_active_power_phase_b",
            name="Output Active Power Phase B",
            native_unit_of_measurement="kW",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_active_power_phase_b",
        ),
        CyberPowerModbusSensorDescription(
            key="output_active_power_phase_c",
            name="Output Active Power Phase C",
            native_unit_of_measurement="kW",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="output_active_power_phase_c",
        ),
        CyberPowerModbusSensorDescription(
            key="load_percent_phase_a",
            name="Load Percent Phase A",
            native_unit_of_measurement="%",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="load_percent_phase_a",
        ),
        CyberPowerModbusSensorDescription(
            key="load_percent_phase_b",
            name="Load Percent Phase B",
            native_unit_of_measurement="%",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="load_percent_phase_b",
        ),
        CyberPowerModbusSensorDescription(
            key="load_percent_phase_c",
            name="Load Percent Phase C",
            native_unit_of_measurement="%",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="load_percent_phase_c",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_voltage",
            name="Battery Voltage",
            native_unit_of_measurement="V",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="battery_voltage",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_current",
            name="Battery Current",
            native_unit_of_measurement="A",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="battery_current",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_temperature",
            name="Battery Temperature",
            native_unit_of_measurement="°C",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="battery_temperature",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_runtime_remaining",
            name="Battery Runtime Remaining",
            native_unit_of_measurement="min",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="battery_runtime_remaining",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_capacity",
            name="Battery Capacity",
            native_unit_of_measurement="%",
            state_class=SensorStateClass.MEASUREMENT,
            register_key="battery_capacity",
        ),
        CyberPowerModbusSensorDescription(
            key="load_on_source",
            name="Load On Source",
            register_key="load_on_source",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_status",
            name="Battery Status",
            register_key="battery_status",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_test_result",
            name="Battery Test Result",
            register_key="battery_test_result",
        ),
        CyberPowerModbusSensorDescription(
            key="battery_maintain_result",
            name="Battery Maintain Result",
            register_key="battery_maintain_result",
        ),
    ]


def get_binary_sensor_descriptions() -> list[CyberPowerModbusBinarySensorDescription]:
    """Return binary sensor descriptions for three-phase devices."""
    return [
        CyberPowerModbusBinarySensorDescription(
            key="battery_connected",
            name="Battery Connected",
            device_class=BinarySensorDeviceClass.BATTERY,
            register_key="battery_connected",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="epo_active",
            name="EPO Active",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="epo_active",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="inverter_capacity_low",
            name="Inverter Capacity Low",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="inverter_capacity_low",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="input_fail",
            name="Input Fail",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="input_fail",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="bypass_sequence_fail",
            name="Bypass Sequence Fail",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="bypass_sequence_fail",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="bypass_voltage_fail",
            name="Bypass Voltage Fail",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="bypass_voltage_fail",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="bypass_fail",
            name="Bypass Fail",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="bypass_fail",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="bypass_overload",
            name="Bypass Overload",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="bypass_overload",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="bypass_overload_timeout",
            name="Bypass Overload Timeout",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="bypass_overload_timeout",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="bypass_untrack",
            name="Bypass Untrack",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="bypass_untrack",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="output_shorted",
            name="Output Shorted",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="output_shorted",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="battery_eod",
            name="Battery End of Discharge",
            device_class=BinarySensorDeviceClass.BATTERY,
            register_key="battery_eod",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="manual_bypass",
            name="Manual Bypass",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="manual_bypass",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="battery_volt_low",
            name="Battery Voltage Low",
            device_class=BinarySensorDeviceClass.BATTERY,
            register_key="battery_volt_low",
        ),
        CyberPowerModbusBinarySensorDescription(
            key="lost_redundant",
            name="Lost Redundancy",
            device_class=BinarySensorDeviceClass.PROBLEM,
            register_key="lost_redundant",
        ),
    ]
