# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Anthony Burow

"""Unified full sensor catalog for profile-level selection and picklists.

This module intentionally contains only static literals (no imports) so
external tools like ups2mqtt can consume it directly.

This catalog is exhaustive/selectable metadata and does not change unified
contract exposure or default-enabled behavior. Canonical `key` values are
authoritative; `aliases` provide alternate names only.

Category taxonomy (catalog metadata only):
- core: primary operational telemetry typically used for baseline monitoring.
- diagnostic: detailed status/fault/auxiliary telemetry for troubleshooting.
- config: device configuration or setpoint-style values.
- metadata: identity/capability/descriptive values, not live telemetry control.
- external: values sourced from external probes or out-of-band probe channels.

Category is classification metadata only and does not imply contract exposure,
default-enabled behavior, or profile membership semantics.
"""

ALL_SENSORS_UNIFIED = {
    "cyberpower_modbus_single_phase": {
        "profile_id": "cyberpower_modbus_single_phase",
        "protocol": "modbus",
        "sensors": [
            {
                "key": "hardware_fault",
                "label": "Hardware Fault",
                "source": "modbus",
                "register": 8192,
                "category": "diagnostic",
            },
            {
                "key": "utility_frequency_out_of_range",
                "label": "Utility Frequency Out of Range",
                "source": "modbus",
                "register": 8200,
                "category": "diagnostic",
            },
            {
                "key": "inverter_off",
                "label": "Inverter Off",
                "source": "modbus",
                "register": 8201,
                "category": "diagnostic",
            },
            {
                "key": "battery_not_present",
                "label": "Battery Not Present",
                "source": "modbus",
                "register": 8206,
                "category": "diagnostic",
            },
            {
                "key": "on_battery_state",
                "aliases": ["battery_discharging"],
                "label": "On Battery",
                "source": "modbus",
                "register": 8209,
                "category": "core",
            },
            {
                "key": "battery_charging",
                "label": "Battery Charging",
                "source": "modbus",
                "register": 8210,
                "category": "diagnostic",
            },
            {
                "key": "battery_fully_charged",
                "label": "Battery Fully Charged",
                "source": "modbus",
                "register": 8212,
                "category": "diagnostic",
            },
            {
                "key": "buzzer_muted",
                "label": "Buzzer Muted",
                "source": "modbus",
                "register": 8224,
                "category": "diagnostic",
            },
            {
                "key": "runtime_low",
                "label": "Runtime Low",
                "source": "modbus",
                "register": 8225,
                "category": "diagnostic",
            },
            {
                "key": "no_output",
                "label": "No Output",
                "source": "modbus",
                "register": 8226,
                "category": "diagnostic",
            },
            {
                "key": "over_temperature",
                "label": "Over Temperature",
                "source": "modbus",
                "register": 8860,
                "category": "diagnostic",
            },
            {
                "key": "input_voltage",
                "aliases": ["utility_voltage"],
                "label": "Input Voltage",
                "source": "modbus",
                "register": 12288,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "input_frequency",
                "aliases": ["utility_frequency"],
                "label": "Input Frequency",
                "source": "modbus",
                "register": 12289,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "output_voltage",
                "label": "Output Voltage",
                "source": "modbus",
                "register": 12320,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "output_load_percent",
                "aliases": ["load_percent"],
                "label": "Output Load",
                "source": "modbus",
                "register": 12327,
                "unit": "%",
                "category": "core",
            },
            {
                "key": "output_power",
                "label": "Output Power",
                "source": "snmp",
                "oid": "1.3.6.1.4.1.3808.1.1.1.4.2.5.0",
                "unit": "W",
                "category": "core",
            },
            {
                "key": "output_energy",
                "label": "Output Energy",
                "source": "snmp",
                "oid": "1.3.6.1.4.1.3808.1.1.1.4.2.6.0",
                "unit": "kWh",
                "category": "core",
            },
            {
                "key": "battery_state_of_charge",
                "aliases": ["battery_capacity"],
                "label": "Battery State of Charge",
                "source": "modbus",
                "register": 12418,
                "unit": "%",
                "category": "core",
            },
            {
                "key": "runtime_remaining",
                "label": "Runtime Remaining",
                "source": "modbus",
                "register": 12419,
                "unit": "min",
                "category": "core",
            },
            {
                "key": "battery_threshold",
                "label": "Battery Threshold",
                "source": "modbus",
                "register": 12435,
                "unit": "%",
                "category": "config",
            },
            {
                "key": "runtime_threshold",
                "label": "Runtime Threshold",
                "source": "modbus",
                "register": 12436,
                "unit": "s",
                "category": "config",
            },
            {
                "key": "model",
                "label": "Model",
                "source": "metadata",
                "category": "metadata",
            },
            {
                "key": "serial_number",
                "label": "Serial Number",
                "source": "metadata",
                "category": "metadata",
            },
            {
                "key": "sw_version",
                "label": "Software Version",
                "source": "metadata",
                "category": "metadata",
            },
            {
                "key": "hw_version",
                "label": "Hardware Version",
                "source": "metadata",
                "category": "metadata",
            },
        ],
    },
    "cyberpower_modbus_three_phase": {
        "profile_id": "cyberpower_modbus_three_phase",
        "protocol": "modbus",
        "sensors": [
            {
                "key": "bypass_voltage_phase_a",
                "label": "Bypass Voltage Phase A",
                "source": "modbus",
                "register": 1,
                "unit": "V",
                "category": "diagnostic",
            },
            {
                "key": "bypass_voltage_phase_b",
                "label": "Bypass Voltage Phase B",
                "source": "modbus",
                "register": 2,
                "unit": "V",
                "category": "diagnostic",
            },
            {
                "key": "bypass_voltage_phase_c",
                "label": "Bypass Voltage Phase C",
                "source": "modbus",
                "register": 3,
                "unit": "V",
                "category": "diagnostic",
            },
            {
                "key": "bypass_current_phase_a",
                "label": "Bypass Current Phase A",
                "source": "modbus",
                "register": 4,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "bypass_current_phase_b",
                "label": "Bypass Current Phase B",
                "source": "modbus",
                "register": 5,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "bypass_current_phase_c",
                "label": "Bypass Current Phase C",
                "source": "modbus",
                "register": 6,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "bypass_frequency_phase_a",
                "label": "Bypass Frequency Phase A",
                "source": "modbus",
                "register": 7,
                "unit": "Hz",
                "category": "diagnostic",
            },
            {
                "key": "bypass_frequency_phase_b",
                "label": "Bypass Frequency Phase B",
                "source": "modbus",
                "register": 8,
                "unit": "Hz",
                "category": "diagnostic",
            },
            {
                "key": "bypass_frequency_phase_c",
                "label": "Bypass Frequency Phase C",
                "source": "modbus",
                "register": 9,
                "unit": "Hz",
                "category": "diagnostic",
            },
            {
                "key": "bypass_pf_phase_a",
                "label": "Bypass PF Phase A",
                "source": "modbus",
                "register": 10,
                "category": "diagnostic",
            },
            {
                "key": "bypass_pf_phase_b",
                "label": "Bypass PF Phase B",
                "source": "modbus",
                "register": 11,
                "category": "diagnostic",
            },
            {
                "key": "bypass_pf_phase_c",
                "label": "Bypass PF Phase C",
                "source": "modbus",
                "register": 12,
                "category": "diagnostic",
            },
            {
                "key": "input_voltage_phase_a",
                "label": "Input Voltage Phase A",
                "source": "modbus",
                "register": 13,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "input_voltage_phase_b",
                "label": "Input Voltage Phase B",
                "source": "modbus",
                "register": 14,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "input_voltage_phase_c",
                "label": "Input Voltage Phase C",
                "source": "modbus",
                "register": 15,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "input_current_phase_a",
                "label": "Input Current Phase A",
                "source": "modbus",
                "register": 16,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "input_current_phase_b",
                "label": "Input Current Phase B",
                "source": "modbus",
                "register": 17,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "input_current_phase_c",
                "label": "Input Current Phase C",
                "source": "modbus",
                "register": 18,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "input_frequency_phase_a",
                "label": "Input Frequency Phase A",
                "source": "modbus",
                "register": 19,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "input_frequency_phase_b",
                "label": "Input Frequency Phase B",
                "source": "modbus",
                "register": 20,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "input_frequency_phase_c",
                "label": "Input Frequency Phase C",
                "source": "modbus",
                "register": 21,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "input_pf_phase_a",
                "label": "Input PF Phase A",
                "source": "modbus",
                "register": 22,
                "category": "diagnostic",
            },
            {
                "key": "input_pf_phase_b",
                "label": "Input PF Phase B",
                "source": "modbus",
                "register": 23,
                "category": "diagnostic",
            },
            {
                "key": "input_pf_phase_c",
                "label": "Input PF Phase C",
                "source": "modbus",
                "register": 24,
                "category": "diagnostic",
            },
            {
                "key": "output_voltage_phase_a",
                "label": "Output Voltage Phase A",
                "source": "modbus",
                "register": 25,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "output_voltage_phase_b",
                "label": "Output Voltage Phase B",
                "source": "modbus",
                "register": 26,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "output_voltage_phase_c",
                "label": "Output Voltage Phase C",
                "source": "modbus",
                "register": 27,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "output_current_phase_a",
                "label": "Output Current Phase A",
                "source": "modbus",
                "register": 28,
                "unit": "A",
                "category": "core",
            },
            {
                "key": "output_current_phase_b",
                "label": "Output Current Phase B",
                "source": "modbus",
                "register": 29,
                "unit": "A",
                "category": "core",
            },
            {
                "key": "output_current_phase_c",
                "label": "Output Current Phase C",
                "source": "modbus",
                "register": 30,
                "unit": "A",
                "category": "core",
            },
            {
                "key": "output_frequency_phase_a",
                "label": "Output Frequency Phase A",
                "source": "modbus",
                "register": 31,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "output_frequency_phase_b",
                "label": "Output Frequency Phase B",
                "source": "modbus",
                "register": 32,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "output_frequency_phase_c",
                "label": "Output Frequency Phase C",
                "source": "modbus",
                "register": 33,
                "unit": "Hz",
                "category": "core",
            },
            {
                "key": "output_pf_phase_a",
                "label": "Output PF Phase A",
                "source": "modbus",
                "register": 34,
                "category": "diagnostic",
            },
            {
                "key": "output_pf_phase_b",
                "label": "Output PF Phase B",
                "source": "modbus",
                "register": 35,
                "category": "diagnostic",
            },
            {
                "key": "output_pf_phase_c",
                "label": "Output PF Phase C",
                "source": "modbus",
                "register": 36,
                "category": "diagnostic",
            },
            {
                "key": "output_apparent_power_phase_a",
                "label": "Output Apparent Power Phase A",
                "source": "modbus",
                "register": 37,
                "unit": "kVA",
                "category": "diagnostic",
            },
            {
                "key": "output_apparent_power_phase_b",
                "label": "Output Apparent Power Phase B",
                "source": "modbus",
                "register": 38,
                "unit": "kVA",
                "category": "diagnostic",
            },
            {
                "key": "output_apparent_power_phase_c",
                "label": "Output Apparent Power Phase C",
                "source": "modbus",
                "register": 39,
                "unit": "kVA",
                "category": "diagnostic",
            },
            {
                "key": "output_active_power_phase_a",
                "label": "Output Active Power Phase A",
                "source": "modbus",
                "register": 40,
                "unit": "kW",
                "category": "core",
            },
            {
                "key": "output_active_power_phase_b",
                "label": "Output Active Power Phase B",
                "source": "modbus",
                "register": 41,
                "unit": "kW",
                "category": "core",
            },
            {
                "key": "output_active_power_phase_c",
                "label": "Output Active Power Phase C",
                "source": "modbus",
                "register": 42,
                "unit": "kW",
                "category": "core",
            },
            {
                "key": "output_reactive_power_phase_a",
                "label": "Output Reactive Power Phase A",
                "source": "modbus",
                "register": 43,
                "unit": "kVAr",
                "category": "diagnostic",
            },
            {
                "key": "output_reactive_power_phase_b",
                "label": "Output Reactive Power Phase B",
                "source": "modbus",
                "register": 44,
                "unit": "kVAr",
                "category": "diagnostic",
            },
            {
                "key": "output_reactive_power_phase_c",
                "label": "Output Reactive Power Phase C",
                "source": "modbus",
                "register": 45,
                "unit": "kVAr",
                "category": "diagnostic",
            },
            {
                "key": "load_percent_phase_a",
                "label": "Load Percent Phase A",
                "source": "modbus",
                "register": 46,
                "unit": "%",
                "category": "core",
            },
            {
                "key": "load_percent_phase_b",
                "label": "Load Percent Phase B",
                "source": "modbus",
                "register": 47,
                "unit": "%",
                "category": "core",
            },
            {
                "key": "load_percent_phase_c",
                "label": "Load Percent Phase C",
                "source": "modbus",
                "register": 48,
                "unit": "%",
                "category": "core",
            },
            {
                "key": "environment_temperature",
                "label": "Environment Temperature",
                "source": "modbus",
                "register": 49,
                "unit": "C",
                "category": "diagnostic",
            },
            {
                "key": "battery_voltage",
                "label": "Battery Voltage",
                "source": "modbus",
                "register": 50,
                "unit": "V",
                "category": "core",
            },
            {
                "key": "battery_current",
                "label": "Battery Current",
                "source": "modbus",
                "register": 52,
                "unit": "A",
                "category": "diagnostic",
            },
            {
                "key": "battery_temperature",
                "label": "Battery Temperature",
                "source": "modbus",
                "register": 54,
                "unit": "C",
                "category": "diagnostic",
            },
            {
                "key": "runtime_remaining",
                "aliases": ["battery_runtime_remaining"],
                "label": "Runtime Remaining",
                "source": "modbus",
                "register": 55,
                "unit": "min",
                "category": "core",
            },
            {
                "key": "battery_state_of_charge",
                "aliases": ["battery_capacity"],
                "label": "Battery State of Charge",
                "source": "modbus",
                "register": 56,
                "unit": "%",
                "category": "core",
            },
            {
                "key": "online_state",
                "aliases": ["load_on_source"],
                "label": "Online State",
                "source": "modbus",
                "register": 81,
                "category": "core",
            },
            {
                "key": "battery_status",
                "label": "Battery Status",
                "source": "modbus",
                "register": 82,
                "category": "diagnostic",
            },
            {
                "key": "battery_connected",
                "label": "Battery Connected",
                "source": "modbus",
                "register": 83,
                "category": "diagnostic",
            },
            {
                "key": "epo_active",
                "label": "EPO Active",
                "source": "modbus",
                "register": 85,
                "category": "diagnostic",
            },
            {
                "key": "inverter_capacity_low",
                "label": "Inverter Capacity Low",
                "source": "modbus",
                "register": 86,
                "category": "diagnostic",
            },
            {
                "key": "input_fail",
                "label": "Input Fail",
                "source": "modbus",
                "register": 88,
                "category": "diagnostic",
            },
            {
                "key": "bypass_sequence_fail",
                "label": "Bypass Sequence Fail",
                "source": "modbus",
                "register": 89,
                "category": "diagnostic",
            },
            {
                "key": "bypass_voltage_fail",
                "label": "Bypass Voltage Fail",
                "source": "modbus",
                "register": 90,
                "category": "diagnostic",
            },
            {
                "key": "bypass_fail",
                "label": "Bypass Fail",
                "source": "modbus",
                "register": 91,
                "category": "diagnostic",
            },
            {
                "key": "bypass_overload",
                "label": "Bypass Overload",
                "source": "modbus",
                "register": 92,
                "category": "diagnostic",
            },
            {
                "key": "bypass_overload_timeout",
                "label": "Bypass Overload Timeout",
                "source": "modbus",
                "register": 93,
                "category": "diagnostic",
            },
            {
                "key": "bypass_untrack",
                "label": "Bypass Untrack",
                "source": "modbus",
                "register": 94,
                "category": "diagnostic",
            },
            {
                "key": "output_shorted",
                "label": "Output Shorted",
                "source": "modbus",
                "register": 96,
                "category": "diagnostic",
            },
            {
                "key": "battery_eod",
                "label": "Battery End of Discharge",
                "source": "modbus",
                "register": 97,
                "category": "diagnostic",
            },
            {
                "key": "battery_test_result",
                "label": "Battery Test Result",
                "source": "modbus",
                "register": 99,
                "category": "diagnostic",
            },
            {
                "key": "battery_maintain_result",
                "label": "Battery Maintain Result",
                "source": "modbus",
                "register": 101,
                "category": "diagnostic",
            },
            {
                "key": "manual_bypass",
                "label": "Manual Bypass",
                "source": "modbus",
                "register": 106,
                "category": "diagnostic",
            },
            {
                "key": "battery_volt_low",
                "label": "Battery Voltage Low",
                "source": "modbus",
                "register": 107,
                "category": "diagnostic",
            },
            {
                "key": "lost_redundant",
                "label": "Lost Redundancy",
                "source": "modbus",
                "register": 112,
                "category": "diagnostic",
            },
            {
                "key": "model",
                "label": "Model",
                "source": "metadata",
                "category": "metadata",
            },
            {
                "key": "serial_number",
                "label": "Serial Number",
                "source": "metadata",
                "category": "metadata",
            },
            {
                "key": "sw_version",
                "label": "Software Version",
                "source": "metadata",
                "category": "metadata",
            },
            {
                "key": "hw_version",
                "label": "Hardware Version",
                "source": "metadata",
                "category": "metadata",
            },
        ],
    },
}
